AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  EksClusterName:
    Description: The name of the EKS cluster already created
    Type: AWS::SSM::Parameter::Value<String>
    Default: CLUSTER_NAME
    NoEcho: true
    ConstraintDescription: You must enter the EKS cluster name

  ClusterRoleName:
    Description: The name of role to access to the EKS cluster
    Type: AWS::SSM::Parameter::Value<String>
    Default: CLUSTER_ROLE_NAME
    NoEcho: true
    ConstraintDescription: You must enter the EKS cluster role name

  GitSourceRepo:
    Description: GitHub source repository - must contain a Dockerfile and buildspec.yml in the base
    Type: AWS::SSM::Parameter::Value<String>
    Default: SOURCE_REPOSITORY
    NoEcho: true
    ConstraintDescription: You must enter a GitHub repository name

  GitBranch:
    Description: GitHub git repository branch - change triggers a new build
    Type: String
    NoEcho: true
    MinLength: 1
    MaxLength: 20
    Default: develop  
    ConstraintDescription: You must enter a GitHub repository branch name

  GitHubToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: GITHUB_TOKEN
    NoEcho: true
    Description: GitHub API token - see https://github.com/blog/1509-personal-api-tokens
    ConstraintDescription: You must enter a GitHub personal access token

  GitHubUser:
    Description: GitHub username or organization
    Type: AWS::SSM::Parameter::Value<String>
    Default: GITHUB_USER
    NoEcho: true
    ConstraintDescription: You must enter a GitHub username or organization

  CodePipelineRoleName:
    Description: Role to be used by codepipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: CODEPIPELINE_ROLE_NAME
    NoEcho: true
    ConstraintDescription: You must enter a role name

  CodeBuildRoleName:
    Description: Role to be used by codebuild
    Type: AWS::SSM::Parameter::Value<String>
    Default: CODEBUILD_ROLE_NAME
    NoEcho: true
    ConstraintDescription: You must enter a role name

  DockerUserName:
    Description: Username to access docker.io
    Type: AWS::SSM::Parameter::Value<String>
    Default: DOCKER_USERNAME
    NoEcho: true
    ConstraintDescription: You must enter a username

  DockerToken:
    Description: Token to access docker.io
    Type: AWS::SSM::Parameter::Value<String>
    Default: DOCKER_TOKEN
    NoEcho: true
    ConstraintDescription: You must enter a token

  KubeConfig:
    Description: Kube_config file to connect to the k8s cluster
    Type: AWS::SSM::Parameter::Value<String>
    Default: KUBE_CONFIG
    #NoEcho: true
    ConstraintDescription: You must enter a kube_config file

  JWTToken:
    Description: Passphrase used to cypher/decypher the content of the JWT
    Type: AWS::SSM::Parameter::Value<String>
    Default: JWT_TOKEN
    NoEcho: true
    ConstraintDescription: You must enter a JWT token value

  Environment:
    Description: Environments to deploy the app
    Type: String
    Default: 'develop'
    AllowedValues:
      - 'develop'
      #- 'production'

Resources:
  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EksClusterName

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Stages:
        - Name: cv-codepipeline
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitSourceRepo
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput
      RoleArn: !Ref CodePipelineRoleName

  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: cv-codebuild
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: DOCKER_USERNAME
            Value: !Ref DockerUserName
          - Name: DOCKER_TOKEN
            Value: !Ref DockerToken
          - Name: KUBE_CONFIG
            Value: !Ref KubeConfig
          - Name: CLUSTER_ROLE_NAME
            Value: !Ref ClusterRoleName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: REPOSITORY_NAME
            Value: !Ref GitSourceRepo
          - Name: REPOSITORY_BRANCH
            Value: !Ref GitBranch
          - Name: REPOSITORY_URI
            Value: docker.io
          - Name: JWT_SECRET
            Value: !Ref JWTToken

      ServiceRole: !Ref CodeBuildRoleName
      Artifacts:
        Type: CODEPIPELINE
        Name: MyBuildOutput
